language: node_js

sudo: false

branches:
  only:
    - master

node_js:
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - node

os:
  - windows
  - linux
  - osx
 
env:
  - NODE_ENV=testing

services:
  - mongodb
  - redis-server
  - docker
  
env:
  - NODE_ENV=testing

cache:
  directories:
    - $HOME/.npm
    - ~/.npm
    - ~/.yarn-cache
    - travis_phantomjs
    - node_modules	
  
before_script:
  - npm install -g eslint
  - npm install -g gulp
  - npm install -g grunt-cli
  - npm install -g bower
  - #echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - bower install -f  
  
after_success:
  - #npm run coveralls
